export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as ResetPassword } from './ResetPassword'
export { default as Main } from './Main'
export { default as Home } from './Home'
export { default as User } from './User'
export { default as Todo } from './Todo'